name: cron_example

on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: python_email_script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASS: ${{ secrets.USER_PASS }}
        run: python email_sender.py

            
    
        