name: cron_example

on:
    schedule:
        - cron: '15 * * * *'

jobs:
  cron_job:
      runs-on: ubuntu-latest
      steps: 
          - name: first_step
            run: echo "Hello Cron"
        