name: cron_example

on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps: 
      - name: first_step
        run: echo "Hello Cron every 45 minutes"
        